
#### Get All doc thu
GET http://localhost:9999/api/docthu

#### Get All doc thu
GET http://localhost:9999/api/docthu/searchdocthu?madonvi=hw0009z

http://localhost:9999/api/docthu/searchbyuser?chuyenquan=tuanpda

#### Get Employee
GET http://localhost:9999/api/docthu/3

POST http://10.42.208.50:9999/api/docthu
content-type: application/json

{
    "madonvi":"hhhh",
    "tendonvi": "dsfsd",
    "mahuyen": "dsfdsfff",
    "diachi": "123wergew"
}