#### Donvi API

#### Get all domvi
GET http://localhost:9999/api/donvi/

#### Find don vi theo huyen
GET http://localhost:9999/api/donvi/searchdonvi?mahuyen=02

#### Find don vi theo ma
GET http://localhost:9999/api/donvi/searchmadv?madonvi=hw0009z